environment:
  TWINE_USERNAME: benfred
  # Note: TWINE_PASSWORD is set in Appveyor settings
  matrix:
    # Nightly 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
      CIBW_SKIP: "*win32* cp27-* cp33-* cp34-* cp35-*"
      CIBW_BEFORE_BUILD: pip install setuptools-rust

# from: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - pip install cibuildwheel==0.9.1 setuptools_rust

build_script:
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
